"""Grok Build auth decision tree. Generated. Do not hand-edit authTree.ts."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".claude/skills/design-explainer/scripts"))
from tree_grammar import Tree  # noqa: E402

HERE = Path(__file__).parent


def build() -> str:
    t = Tree(mk="agb")
    t.set_lane("trigger")
    t.sbox("要打模型", "agent/config.rs", sec="top", snip="gb-resolve")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("環境有 XAI_API_KEY？", sec="top", snip="gb-apikey")
    t.outs(
        c,
        [("AuthMode ApiKey", "不開瀏覽器", False, "top", "gb-apikey")],
        no_label="有",
    )
    t.drop("沒有")
    _, c2 = t.diamond("快取還沒過期？", sec="top", snip="gb-cached")
    t.outs(
        c2,
        [("直接用這張票", "flow.rs", False, "top", "gb-cached")],
        no_label="有",
    )
    t.drop("沒有")
    _, c3 = t.diamond("外部指令成功？", sec="top", snip="gb-external")
    t.outs(
        c3,
        [("別的程式交票", "auth_provider_command", False, "top", "gb-external")],
        no_label="成功",
    )
    t.drop("沒有")
    _, c4 = t.diamond("config 有 oidc？", sec="top", snip="gb-idp")
    t.outs(
        c4,
        [("那個 issuer 的 loopback", "flow.rs", False, "top", "gb-idp")],
        no_label="有",
    )
    t.drop("沒有")
    _, c5 = t.diamond("要裝置碼嗎？", sec="top", snip="gb-device")
    t.outs(
        c5,
        [("螢幕出碼再 poll", "device_code.rs", False, "top", "gb-device")],
        no_label="要",
    )
    t.drop("預設不要")
    t.set_lane("exec")
    t.sbox("綁 127.0.0.1 callback", "oidc/login.rs", sec="top", snip="gb-bind")
    t.drop()
    t.sbox("組 authorize URL", "oidc/protocol.rs", sec="top", snip="gb-authorize")
    t.drop()
    t.sbox("授權碼換票", "oidc/protocol.rs", sec="top", snip="gb-exchange")
    t.drop()
    t.sbox("寫入 AuthMode Oidc", "oidc/protocol.rs", sec="top", snip="gb-write")
    t.drop()
    t.set_lane("fence")
    t.sbox("snapshot 給呼叫端", "auth_provider.rs", sec="top", snip="gb-snapshot")
    html = t.render(did="agb", label="Grok Build 怎麼拿到票")
    m = re.search(r"<svg[\s\S]*</svg>", html)
    if not m:
        raise SystemExit("no svg")
    return m.group(0)


def main() -> None:
    svg = build()
    (HERE / "auth-tree.svg").write_text(svg + "\n")
    (HERE / "authTree.ts").write_text(
        "// Generated by gen_dag.py. Never hand edited.\n"
        "export const AUTH_TREE = " + json.dumps(svg) + ";\n"
    )
    print("wrote", HERE / "authTree.ts", len(svg))


if __name__ == "__main__":
    main()
