"""rhc OAuth trees: login and refresh. Generated. Do not hand-edit the .ts files."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".claude/skills/design-explainer/scripts"))
from tree_grammar import Tree  # noqa: E402

HERE = Path(__file__).parent


def svg_of(html: str) -> str:
    m = re.search(r"<svg[\s\S]*</svg>", html)
    if not m:
        raise SystemExit("no svg")
    return m.group(0)


def login() -> str:
    t = Tree(mk="olog")
    t.set_lane("trigger")
    t.sbox("rhc login", "commands.rs", sec="s-login", snip="loop")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("有 --from-grok？", sec="s-import", snip="import")
    t.outs(
        c,
        [("抄 access token", "grok_import.rs", False, "s-import", "import-session")],
        no_label="有",
    )
    t.drop("沒有")
    t.set_lane("exec")
    t.sbox("綁 127.0.0.1 空埠", "oidc.rs", sec="s-login", snip="loop")
    t.drop()
    t.sbox("產生 PKCE、state、nonce", "oidc.rs", sec="s-login-pkce", snip="pkce")
    t.drop()
    t.sbox("開 auth.x.ai 授權頁", "referrer=rhc", sec="s-login-url", snip="url")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("回呼的 state 對嗎？", sec="s-login-pkce", snip="callback")
    t.outs(
        c,
        [("登入失敗", "state 不符", True, "s-login-pkce", "callback")],
        no_label="不對",
    )
    t.drop("對")
    t.set_lane("exec")
    t.sbox("code + verifier 換票", "oauth2/token", sec="s-login-exchange", snip="exchange")
    t.drop()
    t.set_lane("fence")
    t.sbox("上鎖寫入 auth.json", "store.rs", sec="s-store", snip="save")
    return svg_of(t.render(did="olog", label="rhc login 怎麼拿到票"))


def refresh() -> str:
    t = Tree(mk="oref")
    t.set_lane("trigger")
    t.sbox("要用票", "refresh_if_needed", sec="s-refresh", snip="refresh")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("還沒過期？", sec="s-refresh", snip="fresh")
    t.outs(c, [("直接用", "不上鎖", False, "s-refresh", "fresh")], no_label="是")
    t.drop("過期")
    t.set_lane("fence")
    t.sbox("拿 auth.json.lock", "flock", sec="s-store", snip="lock")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("重讀後已是新票？", sec="s-refresh", snip="refresh")
    t.outs(c, [("用別人換好的", "不再 refresh", False, "s-refresh", "refresh")], no_label="是")
    t.drop("還是舊的")
    t.set_lane("exec")
    t.sbox("refresh_token 換新票", "oauth2/token", sec="s-refresh", snip="refresh-grant")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("伺服器回 invalid_grant？", sec="s-refresh", snip="refresh-grant")
    t.outs(c, [("刪檔，要求重登", "RefreshRevoked", True, "s-refresh", "refresh")], no_label="是")
    t.drop("否")
    t.set_lane("fence")
    t.sbox("寫回新票", "store.rs", sec="s-store", snip="save")
    return svg_of(t.render(did="oref", label="過期的票怎麼換新"))


def main() -> None:
    for name, const, build in (("login", "LOGIN_TREE", login), ("refresh", "REFRESH_TREE", refresh)):
        svg = build()
        (HERE / f"{name}-tree.svg").write_text(svg + "\n")
        (HERE / f"{name}Tree.ts").write_text(
            "// Generated by gen_dag.py. Never hand edited.\n"
            f"export const {const} = " + json.dumps(svg) + ";\n"
        )
        print("wrote", name, len(svg))


if __name__ == "__main__":
    main()
