import type { SeqFlowData } from "../../components/SeqFlow";

/** `rhc login` from the command to the file, checked against oidc.rs, client.rs and store.rs. */
export const LOGIN_FLOW: SeqFlowData = {
  title: "rhc login：從指令到 ~/.rhc/auth.json",
  actors: [
    { id: "you", label: "你", sub: "終端機" },
    { id: "rhc", label: "rhc", sub: "oidc.rs" },
    { id: "listener", label: "本機 listener", sub: "127.0.0.1:port" },
    { id: "browser", label: "瀏覽器" },
    { id: "xai", label: "auth.x.ai" },
    { id: "file", label: "auth.json", sub: "~/.rhc/" },
  ],
  steps: [
    {
      from: "you",
      to: "rhc",
      label: "rhc login",
      fn: ["commands::login", "AuthClient::login"],
      detail: "指令找到 supergrok 這個訂閱，呼叫它的 login。AuthClient::login 把「開瀏覽器」這個動作交給 login_with_browser，裡面再呼叫 run_loopback_flow。",
      snip: "loop",
    },
    {
      from: "rhc",
      to: "listener",
      label: "綁一個隨機 port",
      fn: ["run_loopback_flow"],
      detail: "TcpListener::bind((\"127.0.0.1\", 0)) 讓作業系統挑一個空的 port，redirect_uri 就是 http://127.0.0.1:{port}/callback。只聽本機，外面的機器連不到。",
      snip: "loop",
    },
    {
      from: "rhc",
      to: "rhc",
      label: "產生 PKCE、state、nonce",
      fn: ["generate_pkce", "random_token"],
      detail: "code_verifier 是 32 個隨機 byte。code_challenge 是它的 SHA-256，經 base64url 編碼。state 和 nonce 各是另外 32 個隨機 byte。verifier 留在記憶體，只有 challenge 會出現在網址上。",
      snip: "pkce",
    },
    {
      from: "rhc",
      to: "browser",
      label: "開授權網址",
      fn: ["authorize_url", "webbrowser::open"],
      detail: "網址帶 client_id、redirect_uri、scope、code_challenge（S256）、state、nonce、referrer=rhc，同時印到 stderr，瀏覽器沒自動打開時可以手動貼上。開瀏覽器之前，先開一條執行緒等 callback。",
      snip: "url",
    },
    {
      from: "browser",
      to: "xai",
      label: "你登入並同意",
      detail: "這一步不是 rhc 的程式。你在 auth.x.ai 用 SuperGrok 帳號登入，同意 rhc 要的 scope。",
      snip: "provider",
    },
    {
      from: "xai",
      to: "browser",
      label: "轉回 /callback?code=…&state=…",
      detail: "auth.x.ai 把瀏覽器轉到 redirect_uri，網址帶一次性的授權碼 code，以及原本那個 state。",
    },
    {
      from: "browser",
      to: "listener",
      label: "GET /callback",
      fn: ["accept_callback"],
      detail: "等待的執行緒每 20ms 試一次 accept，最多等 600 秒。路徑不是 /callback 的請求回 404，然後繼續等。",
      snip: "callback",
    },
    {
      from: "listener",
      to: "rhc",
      label: "核對 state，交出 code",
      fn: ["code_from_request_line"],
      detail: "state 對不上就回 400，登入失敗，防止別人把他的 code 塞給你。對上了就回瀏覽器一頁「Signed in」，code 交回主流程。",
      snip: "callback",
    },
    {
      from: "rhc",
      to: "xai",
      label: "用 code 換票",
      fn: ["exchange_code"],
      detail: "POST 到 token 端點：grant_type=authorization_code、code、redirect_uri、client_id、code_verifier。伺服器用 verifier 重算 challenge，確認換票的人就是當初開網址的人。",
      snip: "exchange",
    },
    {
      from: "xai",
      to: "rhc",
      label: "access_token、refresh_token、id_token",
      fn: ["grant_from_token_payload", "claims_from_jwt"],
      detail: "回應帶 access_token、refresh_token、過期秒數和 id_token。rhc 從 id_token 的 claims 讀出 email 與 subject。nonce 目前沒有拿來核對。",
      snip: "claims",
    },
    {
      from: "rhc",
      to: "file",
      label: "上鎖、寫檔",
      fn: ["TokenStore::lock", "TokenStore::save"],
      detail: "先拿 auth.json.lock 的檔案鎖，再寫暫存檔、fsync、權限改 0600，最後 rename 蓋過 auth.json。寫到一半當掉，舊檔還在，不會留下半個 JSON。資料夾是 0700。",
      snip: "save",
    },
    {
      from: "rhc",
      to: "you",
      label: "印出已登入的身分",
      fn: ["into_snapshot", "terminal::print_signed_in"],
      detail: "session 轉成 CredentialSnapshot 回到指令層，終端機印出登入的是誰。",
    },
  ],
};
