"""0.47 Auth decision tree. Generated. Do not hand-edit authTree.ts."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".claude/skills/design-explainer/scripts"))
from tree_grammar import Tree  # noqa: E402

HERE = Path(__file__).parent


def build() -> str:
    t = Tree(mk="a047")
    t.set_lane("trigger")
    t.sbox("要登入或要推論票", "先分安裝包 asar 還是 VM host", sec="s-auth-1")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("這份是安裝包 asar？", sec="s-auth-2")
    t.outs(
        c,
        [("是：沒有 dist/host", "loginCursor 在 main-app.cjs", False, "s-auth-1")],
        no_label="是",
    )
    t.drop("否：VM host")
    t.set_lane("box")
    t.sbox("host-main.cjs 續短票", "cb0ed63，檔界是 // src/host/", sec="s-auth-3")
    t.drop()
    _, c2 = t.diamond("payload 有 grokBotToken？", sec="s-auth-3")
    t.outs(c2, [("可選第二欄", "仍不是 SuperGrok device-code", False, "s-auth-4")])
    t.drop("只有 accessToken")
    t.set_lane("fence")
    t.sbox("identity mint 或 RAM store", "/tmp/sand-identity.sock 是 0.47 才有", sec="s-auth-3")
    html = t.render(did="a047", label="0.47 怎麼拿到票")
    m = re.search(r"<svg[\s\S]*</svg>", html)
    if not m:
        raise SystemExit("no svg")
    return m.group(0)


def main() -> None:
    svg = build()
    (HERE / "auth-tree.svg").write_text(svg + "\n")
    (HERE / "authTree.ts").write_text(
        "// Generated by gen_dag.py. Never hand edited.\n"
        "export const AUTH_TREE = " + json.dumps(svg) + ";\n"
    )
    print("wrote", HERE / "authTree.ts", len(svg))


if __name__ == "__main__":
    main()
