"""Grok Bot auth decision tree. Generated. Do not hand-edit authTree.ts."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".claude/skills/design-explainer/scripts"))
from tree_grammar import Tree  # noqa: E402

HERE = Path(__file__).parent


def build() -> str:
    t = Tree(mk="abot")
    t.set_lane("ui")
    t.sbox("畫面呼叫 loginCursor", "main-edge.ts", sec="s-parts-auth", snip="gb-login")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("開發後端？", sec="s-parts-auth", snip="gb-which")
    t.outs(
        c,
        [("開發站 poll", "cursor-auth.ts", False, "s-auth-2", "gb-which")],
        no_label="是",
    )
    t.drop("不是")
    t.set_lane("exec")
    t.sbox("loginDeepControl 再 poll", "auth/login.ts", sec="s-parts-auth", snip="gb-url")
    t.drop()
    t.set_lane("judge")
    _, c2 = t.diamond("poll 有兩張票？", sec="s-parts-auth", snip="gb-poll")
    t.outs(
        c2,
        [("登入沒完成", "cursor-auth.ts", False, "s-auth-4", "gb-poll")],
        no_label="沒有",
    )
    t.drop("有")
    t.set_lane("exec")
    t.sbox("寫入 sand-secrets.json", "cursor-auth.ts", sec="s-parts-auth", snip="gb-which")
    t.drop()
    t.set_lane("judge")
    _, c3 = t.diamond("這次在 host？", sec="s-parts-auth", snip="gb-start")
    t.outs(
        c3,
        [("安裝包到此為止", "沒有 dist/host", False, "s-auth-4", "gb-login")],
        no_label="不是",
    )
    t.drop("是")
    _, c4 = t.diamond("有續期憑證？", sec="s-parts-auth", snip="gb-host")
    t.outs(
        c4,
        [("短票還等不到", "auth-service.ts", False, "s-auth-4", "gb-host")],
        no_label="沒有",
    )
    t.drop("有")
    t.set_lane("box")
    t.sbox("POST inference-credential", "credential-renewer.ts", sec="s-parts-auth", snip="gb-renew")
    t.drop()
    t.sbox("getAccessToken 交出去", "extension.ts", sec="s-parts-auth", snip="gb-start")
    html = t.render(did="abot", label="Grok Bot 兩張票")
    m = re.search(r"<svg[\s\S]*</svg>", html)
    if not m:
        raise SystemExit("no svg")
    return m.group(0)


def main() -> None:
    svg = build()
    (HERE / "auth-tree.svg").write_text(svg + "\n")
    (HERE / "authTree.ts").write_text(
        "// Generated by gen_dag.py. Never hand edited.\n"
        "export const AUTH_TREE = " + json.dumps(svg) + ";\n"
    )
    print("wrote", HERE / "authTree.ts", len(svg))


if __name__ == "__main__":
    main()
