"""Codex login decision tree. Generated. Do not hand-edit authTree.ts."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".claude/skills/design-explainer/scripts"))
from tree_grammar import Tree  # noqa: E402

HERE = Path(__file__).parent


def build() -> str:
    t = Tree(mk="acx")
    t.set_lane("trigger")
    t.sbox("codex login", "cli/src/main.rs", sec="top", snip="cx-dispatch")
    t.drop()
    t.set_lane("judge")
    _, c = t.diamond("旗標是哪一種？", sec="top", snip="cx-dispatch")
    t.outs(
        c,
        [
            ("兩種 stdin 同時", "直接結束", False, "top", "cx-both"),
            ("舊的 --api-key", "印停用後結束", False, "top", "cx-legacy"),
            ("--with-api-key", "stdin 金鑰寫檔", False, "top", "cx-apikey"),
            ("--device-auth", "device_code_auth.rs", False, "top", "cx-device"),
        ],
        no_label="都沒有",
    )
    t.drop("都沒有")
    t.set_lane("exec")
    t.sbox("本機產生 PKCE", "oauth/pkce.rs", sec="top", snip="cx-pkce")
    t.drop()
    t.sbox("瀏覽器回 localhost", "server.rs", sec="top", snip="cx-open")
    t.drop()
    t.sbox("授權碼換票", "oauth/client.rs", sec="top", snip="cx-exchange")
    t.drop()
    t.sbox("寫入 auth.json", "auth/storage.rs", sec="top", snip="cx-file")
    t.drop()
    t.set_lane("judge")
    _, c2 = t.diamond("讀取時有 CODEX_API_KEY？", sec="top", snip="cx-env")
    t.outs(
        c2,
        [("只放記憶體", "不寫 auth.json", False, "top", "cx-env")],
        no_label="有",
    )
    t.drop("沒有")
    t.set_lane("fence")
    t.sbox("用檔裡的票", "auth/manager.rs", sec="top", snip="cx-save")
    html = t.render(did="acx", label="Codex 怎麼拿到票")
    m = re.search(r"<svg[\s\S]*</svg>", html)
    if not m:
        raise SystemExit("no svg")
    return m.group(0)


def main() -> None:
    svg = build()
    (HERE / "auth-tree.svg").write_text(svg + "\n")
    (HERE / "authTree.ts").write_text(
        "// Generated by gen_dag.py. Never hand edited.\n"
        "export const AUTH_TREE = " + json.dumps(svg) + ";\n"
    )
    print("wrote", HERE / "authTree.ts", len(svg))


if __name__ == "__main__":
    main()
